### ISSUE TITLE
emsdk のリンクが正しくない

### ISSUE THREAD

**Issue by Reputeless** [nokotan/OpenSiv3DWebPage#2]
![image](https://user-images.githubusercontent.com/3108136/134181347-e2bf212d-da4a-4ff5-886f-e1dc93cdfa37.png)

ここの `emsdk github` の URL でダウンロードされるファイルが古いため、`2.0.22-upstream` のインストールができません。
`master` → `main` の変更が原因かも。

**Comment by nokotan** [comment]
そもそもリンク先が zip ファイルをさしていたところから間違っていました。
リンク先を <https://github.com/emscripten-core/emsdk/> に修正しました。
