### ISSUE TITLE
Python インストール手順の説明

### ISSUE THREAD

**Issue by Reputeless** [nokotan/OpenSiv3DWebPage#3]
「python のインストールをカスタマイズする際、pip をインストールすると環境変数に python のパスに追加する設定を有効にしてください。」が本文中に無いため、見落としてしまいます。

**Comment by nokotan** [comment]
本文中にこの記述がないのは意図したものです。(MarkDownの脚注)
以下の観点から、あえてこの一文を脚注にしてあります.

* 遷移先のページの説明では、「インストールのカスタマイズをする」ようには指示されていない
* インストールのカスタマイズをする上級者向けの設定の補足であるが、それをしない場合は不必要な説明であり、本文中にあることで混乱を招き、読み手に対して不親切である

ただし、環境変数の設定については、遷移先のページにも指示があり、間違えやすい点であるため、このプロジェクトサイトにも追記します。
